name: Get branch names on PR
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
     - main
     - testing

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      id-token: write
      contents: read
      checks: write
    steps:
    - name: ref_name
      run: |
        echo "ref_name: ${{ github.ref_name }}"
    - name: head_ref
      run: |
        echo "head_ref: ${{ github.head_ref }}"
    - name: github context (JSON format)
      run: |
        echo "${{ toJSON(github) }}"
    - name: env context
      run: |
        echo "${{ toJSON(env) }}"
    - name: job context
      run: |
        echo "${{ toJSON(job) }}"
    - name: steps context
      run: |
        echo "${{ toJSON(steps) }}"
    - name: runner context
      run: |
        echo "${{ toJSON(runner) }}"
    - name: secrets context
      run: |
        echo "${{ toJSON(secrets) }}" >> log.txt
    - name: context secrets output
      run: cat log.txt
    - name: strategy context
      run: |
        echo "${{ toJSON(strategy) }}"
    - name: matrix context
      run: |
        echo "${{ toJSON(matrix) }}"
    - name: needs context
      run: |
        echo "${{ toJSON(needs) }}"
    - name: inputs context
      run: |
        echo "${{ toJSON(inputs) }}"
